/**
 * Ustalone dopasowania popularnych składników do produktów z bazy. Wzorce działają na nazwie składnika
 * bez ogonków i słów opisowych (patrz cleanedName w foodDb.ts); `en` to opis USDA, dopasowany dokładnie
 * albo jako początek opisu. Wszystko, czego tu nie ma, idzie przez wyszukiwarkę po nazwach.
 * Test (tests/nutrition.test.ts) pilnuje, żeby każdy opis istniał w bazie.
 */
export const ALIASES: [RegExp, string][] = [
  [/^mak\w* (?:ziemniacz|kukurydz)|^skrobi|^krochmal/, 'Cornstarch'],
  [/^mak\w* (?:zytn|razow)/, 'Rye flour, medium'],
  [/^mak\w*( pszenn\w*)?( typ \d+)?$/, 'Wheat flour, white, all-purpose, enriched, bleached'],
  [/^cukr\w* pud/, 'Sugars, powdered'],
  [/^cukr\w* (?:brazow|trzcin)/, 'Sugars, brown'],
  [/^cukier\w*$|^cukr\w*$/, 'Sugars, granulated'],
  [/^masl(?!an)\w*( solon\w*| extra)?$/, 'Butter, salted'],
  [/^mlek\w* (?:odtluszcz|chud|0)/, 'Milk, nonfat, fluid'],
  [/^mlek\w* 2/, 'Milk, reduced fat, fluid, 2% milkfat, with added vitamin A and vitamin D'],
  [/^mlek\w* kokos/, 'Nuts, coconut milk, canned'],
  [/^mlek\w* (?:skondens|zagesz)/, 'Milk, canned, condensed, sweetened'],
  [/^mlek(?:o|a|u|iem)?( \d[.,]?\d*%?| pelne\w*)?$/, 'Milk, whole, 3.25% milkfat, with added vitamin D'],
  [/^kefir|^maslank/, 'Milk, lowfat, fluid, 1% milkfat, with added vitamin A and vitamin D'],
  [/^bialk\w* (?:z )?jaj|^bialko/, 'Egg, white, raw, fresh'],
  [/^zoltk/, 'Egg, yolk, raw, fresh'],
  [/^jaj/, 'Egg, whole, raw, fresh'],
  [/^sol(?:i)?$/, 'Salt, table'],
  [/^oliwk|^oliwek/, 'Olives, ripe, canned (small-extra large)'],
  [/^oliw/, 'Oil, olive, salad or cooking'],
  [/^olej\w* kokos/, 'Oil, coconut'],
  [/^olej\w* slonecz/, 'Oil, sunflower, linoleic (less than 60%)'],
  [/^olej/, 'Oil, canola'],
  [/^smalec|^smalc/, 'Lard'],
  [/^margaryn/, 'Margarine, regular, 80% fat, composite, stick, with salt'],
  [/^majonez/, 'Salad dressing, mayonnaise, regular'],
  [/^cebul/, 'Onions, raw'],
  [/^czosnek|^czosnk/, 'Garlic, raw'],
  [/^ziemniak/, 'Potatoes, flesh and skin, raw'],
  [/^batat/, 'Sweet potato, raw, unprepared'],
  [/^marchew|^marchw/, 'Carrots, raw'],
  [/^pomidor\w* suszon/, 'Tomatoes, sun-dried'],
  [/^(?:koncentrat|przecier)\w* pomidor|^koncentrat/, 'Tomato products, canned, paste, without salt added'],
  [/^passata|^przecier/, 'Tomato products, canned, puree, without salt added'],
  [/^pomidor/, 'Tomatoes, red, ripe, raw, year round average'],
  [/^piers\w* (?:z )?kurczak|^filet\w* (?:z )?kurczak|^kurczak/, 'Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw'],
  [/^indyk|^piers\w* (?:z )?indyk/, 'Turkey, whole, breast, meat only, raw'],
  [/^kacz|^kaczk/, 'Duck, domesticated, meat only, raw'],
  [/^woda$/, 'Beverages, water, tap, drinking'],
  [/^ryz/, 'Rice, white, long-grain, regular, raw, enriched'],
  [/^makaron\w* jajeczn/, 'Noodles, egg, dry, enriched'],
  [/^makaron|^spaghetti|^penne|^fusilli/, 'Pasta, dry, enriched'],
  [/^kasz\w* gryczan/, 'Buckwheat groats, roasted, dry'],
  [/^kasz\w* (?:jeczmien|peczak)|^peczak/, 'Barley, pearled, raw'],
  [/^kasz\w* jaglan|^jagl/, 'Millet, raw'],
  [/^kasz\w* mann|^mann/, 'Semolina, enriched'],
  [/^kuskus|^couscous/, 'Couscous, dry'],
  [/^quinoa|^komosa/, 'Quinoa, uncooked'],
  [/^bulgur/, 'Bulgur, dry'],
  [/^smietan\w* (?:kremowk|30|36|slodk)|^smietank/, 'Cream, fluid, heavy whipping'],
  [/^smietan\w* 12/, 'Cream, fluid, half and half'],
  [/^smietan/, 'Cream, sour, cultured'],
  [/^jogurt/, 'Yogurt, plain, whole milk'],
  [/^ser\w* (?:zolt|gouda|cheddar|edam|tost)|^gouda|^cheddar/, 'Cheese, cheddar'],
  [/^mozzarell/, 'Cheese, mozzarella, whole milk'],
  [/^fet[ay]|^ser\w* fet/, 'Cheese, feta'],
  [/^serek wiejsk|^twarog|^ser\w* twarog/, 'Cheese, cottage, creamed, large or small curd'],
  [/^serek|^ser\w* (?:kremow|smietank)|^philadelphia/, 'Cheese, cream'],
  [/^miod/, 'Honey'],
  [/^kakao/, 'Cocoa, dry powder, unsweetened'],
  [/^czekolad/, 'Chocolate, dark, 70-85% cacao solids'],
  [/^dzem|^konfitur/, 'Jams and preserves'],
  [/^maslo orzech|^maslo z orzech/, 'Peanut butter, smooth style, with salt'],
  [/^banan/, 'Bananas, raw'],
  [/^jablk/, 'Apples, raw, with skin'],
  [/^gruszk/, 'Pears, raw'],
  [/^sliwk/, 'Plums, raw'],
  [/^brzoskwin/, 'Peaches, yellow, raw'],
  [/^wisni|^czeresn/, 'Cherries, sweet, raw'],
  [/^winogron/, 'Grapes, red or green (European type, such as Thompson seedless), raw'],
  [/^kiwi/, 'Kiwifruit, green, raw'],
  [/^mango/, 'Mangos, raw'],
  [/^ananas/, 'Pineapple, raw, all varieties'],
  [/^arbuz/, 'Watermelon, raw'],
  [/^cytryn|^sok z cytryn/, 'Lemons, raw, without peel'],
  [/^pomarancz/, 'Oranges, raw, all commercial varieties'],
  [/^truskawk/, 'Strawberries, raw'],
  [/^malin/, 'Raspberries, raw'],
  [/^borowk/, 'Blueberries, raw'],
  [/^a[vw]okado/, 'Avocados, raw, all commercial varieties'],
  [/^papryk\w* (?:slodk|wedzon|mielon|ostr)|^papryczk\w* (?:chili|mielon)|^chili/, 'Spices, paprika'],
  [/^papryk/, 'Peppers, sweet, red, raw'],
  [/^ogorek|^ogork/, 'Cucumber, with peel, raw'],
  [/^pieczark|^grzyb/, 'Mushrooms, white, raw'],
  [/^szpinak/, 'Spinach, raw'],
  [/^brokul/, 'Broccoli, raw'],
  [/^kalafior/, 'Cauliflower, raw'],
  [/^szparag/, 'Asparagus, raw'],
  [/^fasol\w* szparagow|^fasolk/, 'Beans, snap, green, raw'],
  [/^fasol/, 'Beans, kidney, red, mature seeds, raw'],
  [/^salat|^rukola/, 'Lettuce, cos or romaine, raw'],
  [/^jarmuz/, 'Kale, raw'],
  [/^rzodkiew/, 'Radishes, raw'],
  [/^groszek/, 'Peas, green, raw'],
  [/^kukurydz/, 'Corn, sweet, yellow, raw'],
  [/^soczewic/, 'Lentils, raw'],
  [/^ciecierzyc/, 'Chickpeas (garbanzo beans, bengal gram), mature seeds, raw'],
  [/^kapust\w* kiszon|^kiszon/,'Sauerkraut, canned, solids and liquids'],
  [/^kapust/, 'Cabbage, raw'],
  [/^por$|^pory$|^pora$/, 'Leeks, (bulb and lower leaf-portion), raw'],
  [/^seler/, 'Celery, raw'],
  [/^burak/, 'Beets, raw'],
  [/^dyni/, 'Pumpkin, raw'],
  [/^cukini/, 'Squash, summer, zucchini, includes skin, raw'],
  [/^baklazan/, 'Eggplant, raw'],
  [/^natk|^pietruszk/, 'Parsley, fresh'],
  [/^koper/, 'Dill weed, fresh'],
  [/^imbir/, 'Ginger root, raw'],
  [/^oregano|^tymianek|^tymianku|^bazylia|^bazylii|^majeranek|^majeranku/, 'Spices, oregano, dried'],
  [/^pieprz/, 'Spices, pepper, black'],
  [/^cynamon/, 'Spices, cinnamon, ground'],
  [/^chleb\w* zytn/, 'Bread, rye'],
  [/^chleb|^bulk|^tost/, 'Bread, wheat'],
  [/^orzech\w* wloski|^orzechy$/, 'Nuts, walnuts, english'],
  [/^migdal/, 'Nuts, almonds'],
  [/^slonecznik/, 'Seeds, sunflower seed kernels, dried'],
  [/^platk\w* owsian|^owsian/, 'Cereals, oats, regular and quick, not fortified, dry'],
  [/^szynk/, 'Ham, sliced, regular (approximately 11% fat)'],
  [/^boczek|^boczk/, 'Pork, cured, bacon, unprepared'],
  [/^kielbas/, 'Sausage, Polish, pork and beef, smoked'],
  [/^mies\w* mielon\w* wol|^wolowin\w* mielon|^wolowin/, 'Beef, ground, 85% lean meat / 15% fat, raw'],
  [/^mies\w* mielon|^wieprzowin\w* mielon/, 'Pork, fresh, ground, raw'],
  [/^losos/, 'Fish, salmon, Atlantic, farmed, raw'],
  [/^dorsz/, 'Fish, cod, Atlantic, raw'],
  [/^sledz|^sledzi/, 'Fish, herring, Atlantic, raw'],
  [/^pstrag/, 'Fish, trout, rainbow, farmed, raw'],
  [/^krewetk/, 'Crustaceans, shrimp, mixed species, raw'],
  [/^tunczyk/, 'Fish, tuna, light, canned in water, drained solids'],
  [/^tofu/, 'Tofu, raw, firm, prepared with calcium sulfate'],
  [/^sos sojow/, 'Soy sauce made from soy and wheat (shoyu)'],
  [/^ketchup/, 'Catsup'],
  [/^musztard/, 'Mustard, prepared, yellow'],
  [/^ocet/, 'Vinegar, distilled'],
  [/^drozdz/, "Leavening agents, yeast, baker's, active dry"],
  [/^proszek do pieczenia/, 'Leavening agents, baking powder, double-acting, sodium aluminum sulfate'],
  [/^soda/, 'Leavening agents, baking soda'],
  [/^piwo/, 'Alcoholic beverage, beer, regular, all'],
  [/^wino/, 'Alcoholic beverage, wine, table, red'],
]
